import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Project from '../components/project'
import Main from '../components/Main'
import Toggle from '../components/Toggle'
import {Box1,Box2} from '../components/Box'
import ToDoList from '../components/ToDoList'
import Curvy from '../components/Curvy'
import Three from '../components/Three'
import Svg from '../components/Svg'
import Svg2 from '../components/Svg2'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Main/> */}
      {/* <Toggle/> */}
      {/* <Box1/> */}
      {/* <ToDoList/> */}
      {/* <Box2/> */}
      {/* <Curvy/> */}
      {/* <Three/> */}
      <Svg2/>
    </div>
  )
}
